
!!! curso de Django CRUD (Create, Read, Update and Delete)
1.- Creamos una carpeta de proyecto llamado: "drf_simple_crud" y lo agreagamos al VSCode.
2.- En comando "CMD" ubicamos la ruta del proyecto y verificamos si tenemos Python instalados, veamos
3.- Estando en la ruta: "C:\Proyectos\Django\drf_simple_crud", verificamos la versión de Python: "python --version"
4.- Ahora creamos un modulo virtual para desarrollar el proyecto, le indicamos el siguiente comando: "py -m virtualenv venv" y esperamos unos minutos, luego revisamos en VSCode que exita la carpeta "venv" en nuestro proyecto.
5.- Estando en VSCode, aplicamos F1 y buscamos "Python:Select Interpeter", y le damos clic a la sugerencia que nos indica.
6.- Verificamos que ya estamos trabajando modulo virtual venv, abrimos una consola y verificamos... Ctrl+Shit+ñ 
7.- En caso de que no se muestre en el terminal el modo virtual, activamos el modulo con: ".\venv\Scripts\activate"
8.- Instalamos Django: "pip install django" y verificamos la versión: "django-admin --version"
9.- Limpiams consola (venv) y instalamos: "pip install djangorestframework"
10.- Creamos el proyecto: "django-admin startproject drfsamplecrud"
11.- Ahora hay que enlacar nuestro proyecto con una aplicación.
12.- Vamos a crear una app que a través de API que nos permita obtener proyecto, crear proyecto, actualizar proyecto y eliminarlos. Esto se conoce como un "CRUD"
13.- Creamos la apliación en console (env) con el comando: "py manage.py startapp projects"
14.- Ahora en la sección de [INSTALLED_APPS = ] del archivo "Settings.py" le agregamos el nuevo projecto y el módulo de resftframework para que django lo reconozca, veamos...

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "projects",
    "rest_framework",
]

15.- "py manage.py runserver"
16.- *** SECCIÓN: MODELS (Modelo de Datos...)
19.- Vamos a aprender a crear un modelo de proyecto para que se pueda generar la tabla y luego podemos crear nuesto API ya con la tabla creada de la BD.
20.- Para crear un modelo, tenemos que crearlo en el archivo "models.py", veamos...

from django.db import models


# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    technology = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)


21.- Ahora, en console (env) aplicamos el comando "py manage.py makemigrations". Ejecuta la migraciones pendientes en Django.

# Generated by Django 4.2.3 on 2023-07-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]

22.- Ahora para poder utilizar la BD, tenemos que aplicar el comando: "py manage.py migrate". Esto hace que Django cree las tablas por defecto de forma automática al igual que la tabla Project que se especificó en "models.py"

(venv) C:\Proyectos\Django\drf_simple_crud>py manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, projects, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying projects.0001_initial... OK
  Applying sessions.0001_initial... OK

(venv) C:\Proyectos\Django\drf_simple_crud>

23.- *** SECCIÓN: api (UserSerializer y UserViewSet)...
24.- Para mayor documentación... ver lik: "https://www.django-rest-framework.org"
25.- Instalamaos en console env: "pip install markdown"
26.- Instalamos en console env: "pip install django-filter"

(venv) C:\Proyectos\Django\drf_simple_crud>pip install markdown
Collecting markdown
  Using cached Markdown-3.4.3-py3-none-any.whl (93 kB)
Installing collected packages: markdown
Successfully installed markdown-3.4.3

(venv) C:\Proyectos\Django\drf_simple_crud>pip install django-filter
Collecting django-filter
  Downloading django_filter-23.2-py3-none-any.whl (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.9/91.9 kB 436.6 kB/s eta 0:00:00      
Requirement already satisfied: Django>=3.2 in c:\proyectos\django\drf_simple_crud\venv\lib\site-packages (from django-filter) (4.2.3)
Requirement already satisfied: asgiref<4,>=3.6.0 in c:\proyectos\django\drf_simple_crud\venv\lib\site-packages (from Django>=3.2->django-filter) (3.7.2)
Requirement already satisfied: sqlparse>=0.3.1 in c:\proyectos\django\drf_simple_crud\venv\lib\site-packages (from Django>=3.2->django-filter) (0.4.4)
Requirement already satisfied: tzdata in c:\proyectos\django\drf_simple_crud\venv\lib\site-packages (from Django>=3.2->django-filter) (2023.3)
Installing collected packages: django-filter
Successfully installed django-filter-23.2

27.- En la carpeta "projects" creamos un archivo llamado: "serializers.py", veamos...
28.- Estos serializers nos van a permitir es poder llamar un modulo especial en rest_framework, veamos...

from rest_framework import serializers
from .models import Project


class ProjectSerializer(serializers.ModelSerializer):
    class Meta:
        model = Project
        fields = ("id", "title", "description", "technology", "created_at")
        read_only_fields = ("created_at",)

		
29.- Ahora crearemos el ViewSet, ya que nos permite consultar el Serializer y que peticiones se pueden hacer o por ejemplo de enviar una serie de autentificaciones para poder hacerlo. 
30.- Ven la carpeta "projects" creamos un archivo llamado "api.py", veamos...

from .models import Project
from rest_framework import viewsets, permissions
from .serializers import ProjectSerializer


class ProjectViewSet(viewsets.ModelViewSet):
    queryset = Project.objects.all()
    permissions_classes = [permissions.AllowAny]
    seralizer_class = ProjectSerializer


31.- Ahora, crearemos el "urls.py", veamos...

from rest_framework import routers
from .api import ProjectViewSet

router = routers.DefaultRouter()
router.register("api/projets", ProjectViewSet, "projects")

urlpatterns = router.urls

32.- tenemos ya las Urls pero mi aplicai+o principal no las conoce, para eso tenemos que ir al "urls.py" del proyecto:

from django.contrib import admin
from django.urls import path, include


urlpatterns = [path("admin/", admin.site.urls), path("", include("projects.urls"))]

33.- En el navegador: http://127.0.0.1:8000/api/projects/    cargamos un registro con POST y nos muestra un contenido tipo Json:

[
    {
        "id": 1,
        "title": "Mi primer proyecto",
        "description": "Utilizando Django Rest Framework",
        "technology": "Python",
        "created_at": "2023-07-04T17:39:03.867066Z"
    }
]

34.- En VSCode vamos a instalar una Extensión llamada: "Thunder Client". Es una extensión de cliente Rest API liviana.
35.- New Request y colocamos la url: http://127.0.0.1:8000/api/projects    y nos muestra:
[
  {
    "id": 1,
    "title": "Mi primer proyecto",
    "description": "Utilizando Django Rest Framework",
    "technology": "Python",
    "created_at": "2023-07-04T17:39:03.867066Z"
  }
]

36.- Ahora, hacemos una petición "POST" , "Body" , "Json": 
{
  "title":"Mi segundo proyecto",
  "description": "Utilizando Thunder Client",
  "technology": "VSCode"
}

37.- Clic botón [Send] y muestra:

{
  "id": 2,
  "title": "Mi segundo proyecto",
  "description": "Utilizando Thunder Client",
  "technology": "VSCode",
  "created_at": "2023-07-04T17:55:36.714332Z"
}

38.- Ahora hacemos una petición "GET" de todos los proyectos y clic en [Send], veamos...

[
  {
    "id": 1,
    "title": "Mi primer proyecto",
    "description": "Utilizando Django Rest Framework",
    "technology": "Python",
    "created_at": "2023-07-04T17:39:03.867066Z"
  },
  {
    "id": 2,
    "title": "Mi segundo proyecto",
    "description": "Utilizando Thunder Client",
    "technology": "VSCode",
    "created_at": "2023-07-04T17:55:36.714332Z"
  }
]
 
39.- También podemos consultar a través de la URL, ejemplo: http://127.0.0.1:8000/api/projects/2   y luego clic botón [Send]
40.- Para Actualizar un campo en específico utilizamos la petición "PATH", veamos un ejemplo del ID:1 actualizamos el "title".

{
  "title":"Utilizando la petición PATHC"
}

41.- En la petición "GET" nos muestra: 

{
  "id": 1,
  "title": "Utilizando la petición PATHC",
  "description": "Utilizando Django Rest Framework",
  "technology": "Python",
  "created_at": "2023-07-04T17:39:03.867066Z"
}

42.- Hasta ahora lo hemos hecho de forma localHost, sin embargo, hay que aprender a ejecutarlo desde la nube con Render, veamos...

43.- *** SECCIÓN: Deploy...
44.- Primero que todo, vamos aa subir el proyecto a un repositorio "GITBUH", en console aplicamos el comando:

(venv) C:\Proyectos\Django\drf_simple_crud>git init
Initialized empty Git repository in C:/Proyectos/Django/drf_simple_crud/.git/

45.- Creamos en la raíz del repositorio el archivo git: ".gitignore" con las líeas de comandos:

db.sqlite3
venv
__pycache__

46.- luego el comando:


47.- Aplicamos el comando en console: "git add ."
48.- Aplicamos el comando en console: 'git commit -m "Comentario"'
49.-
50.-
51.-
52.-
53.-
54.-
55.-
56.-
57.-
58.-
59.-
60.-
61.-
62.-
63.-
64.-
65.-
66.-
67.-
68.-
69.-
70.-
71.-
72.-
73.-
74.-
75.-
76.-
77.-
78.-
79.-
80.-
81.-
82.-
83.-
84.-
85.-
86.-
87.-
88.-
89.-
90.-
91.-
92.-
93.-
94.-
95.-
96.-
97.-
98.-
99.-
100.-
101.-
102.-
103.-
104.-
105.-
106.-
107.-
108.-
109.-
110.-
111.-
112.-
113.-
114.-
115.-
116.-
117.-
118.-
119.-
120.-
121.-
122.-
123.-
124.-
125.-
126.-
127.-
128.-
129.-
130.-
131.-
132.-
133.-
134.-
135.-
136.-
137.-
138.-
139.-
140.-
141.-
142.-
143.-
144.-
145.-
146.-
147.-
148.-
149.-
150.-
151.-
152.-
153.-
154.-
155.-
156.-
157.-
158.-
159.-
160.-
161.-
162.-
163.-
164.-
165.-
166.-
167.-
168.-
169.-
170.-
171.-
172.-
173.-
174.-
175.-
176.-
